{"dcowden.cadquery/cq_cmd.py": {"loc": 197, "lloc": 133, "sloc": 143, "comments": 16, "multi": 0, "blank": 38, "single_comments": 16}, "dcowden.cadquery/runtests.py": {"loc": 24, "lloc": 16, "sloc": 16, "comments": 5, "multi": 0, "blank": 3, "single_comments": 5}, "dcowden.cadquery/setup.py": {"loc": 57, "lloc": 6, "sloc": 39, "comments": 16, "multi": 0, "blank": 4, "single_comments": 14}, "dcowden.cadquery/cadquery/cq.py": {"loc": 2734, "lloc": 893, "sloc": 780, "comments": 162, "multi": 1181, "blank": 627, "single_comments": 146}, "dcowden.cadquery/cadquery/cqgi.py": {"loc": 500, "lloc": 268, "sloc": 261, "comments": 28, "multi": 110, "blank": 103, "single_comments": 26}, "dcowden.cadquery/cadquery/cq_directive.py": {"loc": 85, "lloc": 41, "sloc": 52, "comments": 7, "multi": 3, "blank": 23, "single_comments": 7}, "dcowden.cadquery/cadquery/selectors.py": {"loc": 664, "lloc": 264, "sloc": 269, "comments": 42, "multi": 205, "blank": 153, "single_comments": 37}, "dcowden.cadquery/cadquery/__init__.py": {"loc": 25, "lloc": 11, "sloc": 16, "comments": 3, "multi": 0, "blank": 6, "single_comments": 3}, "dcowden.cadquery/cadquery/contrib/__init__.py": {"loc": 18, "lloc": 1, "sloc": 0, "comments": 0, "multi": 14, "blank": 4, "single_comments": 0}, "dcowden.cadquery/cadquery/freecad_impl/console_logging.py": {"loc": 111, "lloc": 45, "sloc": 42, "comments": 15, "multi": 33, "blank": 20, "single_comments": 16}, "dcowden.cadquery/cadquery/freecad_impl/exporters.py": {"loc": 383, "lloc": 172, "sloc": 231, "comments": 31, "multi": 44, "blank": 80, "single_comments": 28}, "dcowden.cadquery/cadquery/freecad_impl/geom.py": {"loc": 762, "lloc": 359, "sloc": 370, "comments": 45, "multi": 194, "blank": 155, "single_comments": 43}, "dcowden.cadquery/cadquery/freecad_impl/importers.py": {"loc": 74, "lloc": 43, "sloc": 41, "comments": 8, "multi": 9, "blank": 16, "single_comments": 8}, "dcowden.cadquery/cadquery/freecad_impl/shapes.py": {"loc": 1046, "lloc": 506, "sloc": 453, "comments": 47, "multi": 342, "blank": 200, "single_comments": 51}, "dcowden.cadquery/cadquery/freecad_impl/__init__.py": {"loc": 159, "lloc": 52, "sloc": 100, "comments": 18, "multi": 22, "blank": 18, "single_comments": 19}, "dcowden.cadquery/cadquery/plugins/__init__.py": {"loc": 18, "lloc": 1, "sloc": 0, "comments": 0, "multi": 15, "blank": 3, "single_comments": 0}, "dcowden.cadquery/doc/conf.py": {"loc": 276, "lloc": 26, "sloc": 42, "comments": 158, "multi": 14, "blank": 68, "single_comments": 152}, "dcowden.cadquery/examples/FreeCAD/Ex014_Offset_Workplanes.py": {"loc": 20, "lloc": 5, "sloc": 5, "comments": 11, "multi": 0, "blank": 4, "single_comments": 11}, "dcowden.cadquery/examples/FreeCAD/Ex001_Simple_Block.py": {"loc": 19, "lloc": 6, "sloc": 6, "comments": 12, "multi": 0, "blank": 4, "single_comments": 9}, "dcowden.cadquery/examples/FreeCAD/Ex002_Block_With_Bored_Center_Hole.py": {"loc": 20, "lloc": 7, "sloc": 8, "comments": 13, "multi": 0, "blank": 3, "single_comments": 9}, "dcowden.cadquery/examples/FreeCAD/Ex003_Pillow_Block_With_Counterbored_Holes.py": {"loc": 34, "lloc": 10, "sloc": 14, "comments": 24, "multi": 0, "blank": 3, "single_comments": 17}, "dcowden.cadquery/examples/FreeCAD/Ex004_Extruded_Cylindrical_Plate.py": {"loc": 29, "lloc": 7, "sloc": 9, "comments": 21, "multi": 0, "blank": 3, "single_comments": 17}, "dcowden.cadquery/examples/FreeCAD/Ex005_Extruded_Lines_and_Arcs.py": {"loc": 45, "lloc": 5, "sloc": 10, "comments": 34, "multi": 0, "blank": 3, "single_comments": 32}, "dcowden.cadquery/examples/FreeCAD/Ex006_Moving_the_Current_Working_Point.py": {"loc": 35, "lloc": 8, "sloc": 8, "comments": 23, "multi": 0, "blank": 6, "single_comments": 21}, "dcowden.cadquery/examples/FreeCAD/Ex007_Using_Point_Lists.py": {"loc": 32, "lloc": 9, "sloc": 9, "comments": 20, "multi": 0, "blank": 6, "single_comments": 17}, "dcowden.cadquery/examples/FreeCAD/Ex008_Polygon_Creation.py": {"loc": 39, "lloc": 8, "sloc": 11, "comments": 30, "multi": 0, "blank": 3, "single_comments": 25}, "dcowden.cadquery/examples/FreeCAD/Ex009_Polylines.py": {"loc": 39, "lloc": 5, "sloc": 16, "comments": 19, "multi": 0, "blank": 4, "single_comments": 19}, "dcowden.cadquery/examples/FreeCAD/Ex010_Defining_an_Edge_with_a_Spline.py": {"loc": 27, "lloc": 6, "sloc": 14, "comments": 8, "multi": 0, "blank": 5, "single_comments": 8}, "dcowden.cadquery/examples/FreeCAD/Ex011_Mirroring_Symmetric_Geometry.py": {"loc": 20, "lloc": 5, "sloc": 5, "comments": 11, "multi": 0, "blank": 4, "single_comments": 11}, "dcowden.cadquery/examples/FreeCAD/Ex012_Creating_Workplanes_on_Faces.py": {"loc": 16, "lloc": 4, "sloc": 4, "comments": 9, "multi": 0, "blank": 3, "single_comments": 9}, "dcowden.cadquery/examples/FreeCAD/Ex013_Locating_a_Workplane_on_a_Vertex.py": {"loc": 21, "lloc": 5, "sloc": 5, "comments": 12, "multi": 0, "blank": 4, "single_comments": 12}, "dcowden.cadquery/examples/FreeCAD/Ex015_Rotated_Workplanes.py": {"loc": 22, "lloc": 3, "sloc": 6, "comments": 14, "multi": 0, "blank": 2, "single_comments": 14}, "dcowden.cadquery/examples/FreeCAD/Ex016_Using_Construction_Geometry.py": {"loc": 21, "lloc": 3, "sloc": 6, "comments": 13, "multi": 0, "blank": 2, "single_comments": 13}, "dcowden.cadquery/examples/FreeCAD/Ex017_Shelling_to_Create_Thin_Features.py": {"loc": 14, "lloc": 3, "sloc": 3, "comments": 9, "multi": 0, "blank": 2, "single_comments": 9}, "dcowden.cadquery/examples/FreeCAD/Ex018_Making_Lofts.py": {"loc": 20, "lloc": 3, "sloc": 6, "comments": 12, "multi": 0, "blank": 2, "single_comments": 12}, "dcowden.cadquery/examples/FreeCAD/Ex019_Counter_Sunk_Holes.py": {"loc": 19, "lloc": 3, "sloc": 5, "comments": 12, "multi": 0, "blank": 2, "single_comments": 12}, "dcowden.cadquery/examples/FreeCAD/Ex020_Rounding_Corners_with_Fillets.py": {"loc": 13, "lloc": 3, "sloc": 3, "comments": 8, "multi": 0, "blank": 2, "single_comments": 8}, "dcowden.cadquery/examples/FreeCAD/Ex021_Splitting_an_Object.py": {"loc": 25, "lloc": 4, "sloc": 5, "comments": 17, "multi": 0, "blank": 3, "single_comments": 17}, "dcowden.cadquery/examples/FreeCAD/Ex022_Classic_OCC_Bottle.py": {"loc": 19, "lloc": 7, "sloc": 9, "comments": 5, "multi": 0, "blank": 5, "single_comments": 5}, "dcowden.cadquery/examples/FreeCAD/Ex023_Parametric_Enclosure.py": {"loc": 77, "lloc": 42, "sloc": 48, "comments": 27, "multi": 0, "blank": 17, "single_comments": 12}, "dcowden.cadquery/examples/FreeCAD/Ex024_Using_FreeCAD_Solids_as_CQ_Objects.py": {"loc": 23, "lloc": 10, "sloc": 10, "comments": 7, "multi": 0, "blank": 6, "single_comments": 7}, "dcowden.cadquery/examples/FreeCAD/Ex025_Revolution.py": {"loc": 21, "lloc": 6, "sloc": 6, "comments": 11, "multi": 0, "blank": 4, "single_comments": 11}, "dcowden.cadquery/examples/FreeCAD/Ex026_Lego_Brick.py": {"loc": 56, "lloc": 29, "sloc": 34, "comments": 17, "multi": 0, "blank": 9, "single_comments": 13}, "dcowden.cadquery/examples/FreeCAD/Ex027_Remote_Enclosure.py": {"loc": 85, "lloc": 33, "sloc": 67, "comments": 30, "multi": 0, "blank": 11, "single_comments": 7}, "dcowden.cadquery/examples/FreeCAD/Ex028_Numpy.py": {"loc": 25, "lloc": 7, "sloc": 15, "comments": 6, "multi": 0, "blank": 4, "single_comments": 6}, "dcowden.cadquery/examples/FreeCAD/Ex029_Braille.py": {"loc": 184, "lloc": 99, "sloc": 117, "comments": 16, "multi": 13, "blank": 35, "single_comments": 19}, "dcowden.cadquery/examples/FreeCAD/Ex030_Panel_with_Various_Holes_for_Connector_Installation.py": {"loc": 45, "lloc": 28, "sloc": 28, "comments": 4, "multi": 0, "blank": 13, "single_comments": 4}, "dcowden.cadquery/examples/FreeCAD/Ex031_Sweep.py": {"loc": 40, "lloc": 15, "sloc": 19, "comments": 11, "multi": 0, "blank": 10, "single_comments": 11}, "dcowden.cadquery/examples/FreeCAD/Ex032_3D_Printer_Extruder_Support.py": {"loc": 215, "lloc": 95, "sloc": 126, "comments": 56, "multi": 13, "blank": 52, "single_comments": 24}, "dcowden.cadquery/examples/FreeCAD/Ex033_Shelled_Cube_Inside_Chamfer_With_Logical_Selector_Operators.py": {"loc": 10, "lloc": 3, "sloc": 6, "comments": 2, "multi": 0, "blank": 2, "single_comments": 2}, "dcowden.cadquery/examples/FreeCAD/Ex034_Sweep_Along_List_Of_Wires.py": {"loc": 47, "lloc": 13, "sloc": 25, "comments": 10, "multi": 0, "blank": 12, "single_comments": 10}, "dcowden.cadquery/examples/FreeCAD/Ex035_Reinforce_Junction_UsingFillet.py": {"loc": 29, "lloc": 5, "sloc": 9, "comments": 15, "multi": 0, "blank": 5, "single_comments": 15}, "dcowden.cadquery/tests/TestCadObjects.py": {"loc": 527, "lloc": 312, "sloc": 325, "comments": 73, "multi": 45, "blank": 91, "single_comments": 66}, "dcowden.cadquery/tests/TestCadQuery.py": {"loc": 1686, "lloc": 859, "sloc": 959, "comments": 260, "multi": 213, "blank": 309, "single_comments": 205}, "dcowden.cadquery/tests/TestCQGI.py": {"loc": 208, "lloc": 93, "sloc": 165, "comments": 1, "multi": 7, "blank": 35, "single_comments": 1}, "dcowden.cadquery/tests/TestCQSelectors.py": {"loc": 503, "lloc": 281, "sloc": 321, "comments": 73, "multi": 8, "blank": 113, "single_comments": 61}, "dcowden.cadquery/tests/TestExporters.py": {"loc": 52, "lloc": 32, "sloc": 30, "comments": 3, "multi": 8, "blank": 11, "single_comments": 3}, "dcowden.cadquery/tests/TestImporters.py": {"loc": 67, "lloc": 34, "sloc": 30, "comments": 10, "multi": 14, "blank": 13, "single_comments": 10}, "dcowden.cadquery/tests/TestLogging.py": {"loc": 101, "lloc": 76, "sloc": 76, "comments": 4, "multi": 0, "blank": 21, "single_comments": 4}, "dcowden.cadquery/tests/TestWorkplanes.py": {"loc": 125, "lloc": 80, "sloc": 78, "comments": 14, "multi": 3, "blank": 29, "single_comments": 15}, "dcowden.cadquery/tests/__init__.py": {"loc": 66, "lloc": 37, "sloc": 46, "comments": 0, "multi": 0, "blank": 19, "single_comments": 1}}
